import AppKit
import CryptoKit
import Foundation

/// Keeps the text you copy anywhere on the Mac, so it can be found and copied again later.
///
/// Watches the clipboard twice a second (macOS has no notification for it). Only plain text is
/// kept. Passwords and other secrets are skipped: password managers mark what they copy as
/// concealed or transient, and the apps listed in `privateApps` are never read at all. Items older
/// than the retention time are deleted, except starred ones, which stay until you delete them.
@MainActor
final class ClipboardStore: ObservableObject {
    /// Copies longer than this are not kept (a whole book, a log file): they would slow searching.
    static let maxCharacters = 200_000
    /// Newest items kept besides the starred ones, whatever the retention time...
    static let maxItems = 5_000
    /// ...and at most this much text in all, so searching stays instant (starred items not counted).
    static let maxTotalCharacters = 20_000_000
    /// Items the list shows at once; search reaches all of them.
    static let listLimit = 400
    static let previewLength = 600

    /// Marks that password managers and other apps put on the clipboard to ask not to be recorded
    /// (nspasteboard.org).
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// Apps whose copies are never kept, whatever they put on the clipboard.
    private static let privateApps: Set<String> = [
        "com.apple.Passwords",
        "com.apple.keychainaccess",
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.lastpass.LastPass",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.dashlanephonefinal",
    ]

    @Published private(set) var items: [ClipItem] = []
    @Published private(set) var total = 0
    @Published private(set) var starredTotal = 0
    @Published var search = "" {
        didSet { reload() }
    }
    @Published var starredOnly = false {
        didSet { reload() }
    }
    @Published private(set) var lastError: String?

    private let db: Database?
    private let settings: AppSettings
    private let work = DispatchQueue(label: "navo.clipboard", qos: .utility)
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    /// Clipboard changes Navo made itself when copying an item again: not recorded again.
    private var ownChangeCounts: Set<Int> = []
    private var savesSincePrune = 0

    init(db: Database?, settings: AppSettings) {
        self.db = db
        self.settings = settings
        prune()
        reload()
    }

    // MARK: Watching

    func start() {
        // The demo shows sample copies only: your real clipboard is not read.
        guard settings.clipboardHistory, db != nil, timer == nil, !Paths.isDemo else { return }
        lastChangeCount = NSPasteboard.general.changeCount // what was there before is not a new copy
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            guard let self else { return }
            MainActor.assumeIsolated {
                self.check()
            }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Follows the setting.
    func applySetting() {
        if settings.clipboardHistory {
            start()
        } else {
            stop()
        }
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        if ownChangeCounts.remove(count) != nil { return }

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        // A copied file puts its name on the clipboard as text too: that is not text you copied.
        guard !types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        if let bundle = app?.bundleIdentifier, Self.privateApps.contains(bundle) { return }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }
        guard text.utf16.count <= Self.maxCharacters * 2, text.count <= Self.maxCharacters else { return }
        save(text, appName: app?.localizedName, appBundleID: app?.bundleIdentifier)
    }

    private func save(_ text: String, appName: String?, appBundleID: String?) {
        guard let db else { return }
        let now = Date()
        // Hashing and the search key take a moment for long text: off the main thread.
        weak var store = self
        work.async {
            let hash = ClipboardStore.hash(text)
            var problem: String?
            do {
                try db.saveClip(
                    id: UUID().uuidString,
                    text: text,
                    hash: hash,
                    copiedAt: now,
                    appName: appName,
                    appBundleID: appBundleID,
                    searchText: TextTools.searchKey(text)
                )
            } catch {
                problem = error.localizedDescription
            }
            let result = problem
            DispatchQueue.main.async {
                MainActor.assumeIsolated {
                    store?.saved(problem: result)
                }
            }
        }
    }

    /// What tells two copies of the same text apart from two different texts.
    nonisolated static func hash(_ text: String) -> String {
        SHA256.hash(data: Data(text.utf8)).map { String(format: "%02x", $0) }.joined()
    }

    private func saved(problem: String?) {
        lastError = problem
        savesSincePrune += 1
        if savesSincePrune >= 50 {
            prune()
        }
        reload()
    }

    // MARK: Browsing

    func reload() {
        guard let db else { return }
        do {
            items = try db.clips(search: search, starredOnly: starredOnly, limit: Self.listLimit, previewLength: Self.previewLength)
            let counts = try db.clipCount()
            total = counts.all
            starredTotal = counts.starred
        } catch {
            lastError = error.localizedDescription
        }
    }

    func fullText(_ id: String) -> String? {
        try? db?.clipText(id: id)
    }

    /// Puts an item back on the clipboard, ready to paste.
    @discardableResult
    func copy(_ id: String) -> Bool {
        guard let text = fullText(id) else { return false }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        ownChangeCounts.insert(pasteboard.changeCount)
        return true
    }

    /// The newest copies, or the ones matching `query`, for the quick list.
    func recent(matching query: String, limit: Int) -> [ClipItem] {
        guard let db else { return [] }
        do {
            return try db.clips(search: query, starredOnly: false, limit: limit, previewLength: 300)
        } catch {
            lastError = error.localizedDescription
            return []
        }
    }

    /// Puts an item back on the clipboard and makes it the newest, since it was just used.
    @discardableResult
    func use(_ id: String) -> Bool {
        guard copy(id) else { return false }
        do {
            try db?.touchClip(id: id, at: Date())
        } catch {
            lastError = error.localizedDescription
        }
        reload()
        return true
    }

    func setStarred(_ id: String, _ starred: Bool) {
        do {
            try db?.setClipStarred(id: id, starred: starred)
        } catch {
            lastError = error.localizedDescription
        }
        reload()
    }

    /// Deletes one item permanently.
    func delete(_ id: String) {
        do {
            try db?.deleteClip(id: id)
        } catch {
            lastError = error.localizedDescription
        }
        reload()
    }

    /// Deletes everything that is not starred, permanently.
    func clearUnstarred() {
        do {
            try db?.deleteUnstarredClips()
            try db?.compact()
        } catch {
            lastError = error.localizedDescription
        }
        reload()
    }

    /// Applies the retention time and the item limit. Starred items are never removed.
    func prune() {
        savesSincePrune = 0
        guard let db else { return }
        let cutoff = Date().addingTimeInterval(-Double(settings.clipboardDays) * 86_400)
        do {
            if try db.pruneClips(before: cutoff, keep: Self.maxItems, maxCharacters: Self.maxTotalCharacters) > 0 {
                reload()
            }
        } catch {
            lastError = error.localizedDescription
        }
    }
}
